Importing libraries

In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import classification_report,confusion_matrix

In [2]:
spam_email_data = pd.read_csv("spambase.data")
spam_email_data.columns = ['word_freq_make','word_freq_address','word_freq_all', 'word_freq_3d','word_freq_our','word_freq_over','word_freq_remove', 'word_freq_internet','word_freq_order','word_freq_mail','word_freq_receive','word_freq_will','word_freq_people','word_freq_report','word_freq_addresses','word_freq_free','word_freq_business','word_freq_email','word_freq_you','word_freq_credit','word_freq_your','word_freq_font','word_freq_000','word_freq_money','word_freq_hp','word_freq_hpl','word_freq_george','word_freq_650','word_freq_lab','word_freq_labs','word_freq_telnet','word_freq_857','word_freq_data','word_freq_415','word_freq_85','word_freq_technology','word_freq_1999','word_freq_parts','word_freq_pm','word_freq_direct','word_freq_cs','word_freq_meeting','word_freq_original','word_freq_project','word_freq_re','word_freq_edu','word_freq_table','word_freq_conference','char_freq_;','char_freq_(','char_freq_[','char_freq_!','char_freq_$','char_freq_#','capital_run_length_average','capital_run_length_longest','capital_run_length_total','spam_or_not_spam']
spam_email_data.head()

word_freq_make  word_freq_address  word_freq_all  word_freq_3d  \
0            0.21               0.28           0.50           0.0   
1            0.06               0.00           0.71           0.0   
2            0.00               0.00           0.00           0.0   
3            0.00               0.00           0.00           0.0   
4            0.00               0.00           0.00           0.0   

   word_freq_our  word_freq_over  word_freq_remove  word_freq_internet  \
0           0.14            0.28              0.21                0.07   
1           1.23            0.19              0.19                0.12   
2           0.63            0.00              0.31                0.63   
3           0.63            0.00              0.31                0.63   
4           1.85            0.00              0.00                1.85   

   word_freq_order  word_freq_mail  ...  char_freq_;  char_freq_(  \
0             0.00            0.94  ...         0.00        0.132   
1             0.64            0.25  ...         0.01        0.143   
2             0.31            0.63  ...         0.00        0.137   
3             0.31            0.63  ...         0.00        0.135   
4             0.00            0.00  ...         0.00        0.223   

   char_freq_[  char_freq_!  char_freq_$  char_freq_#  \
0          0.0        0.372        0.180        0.048   
1          0.0        0.276        0.184        0.010   
2          0.0        0.137        0.000        0.000   
3          0.0        0.135        0.000        0.000   
4          0.0        0.000        0.000        0.000   

   capital_run_length_average  capital_run_length_longest  \
0                       5.114                         101   
1                       9.821                         485   
2                       3.537                          40   
3                       3.537                          40   
4                       3.000                          15   

   capital_run_length_total  spam_or_not_spam  
0                      1028                 1  
1                      2259                 1  
2                       191                 1  
3                       191                 1  
4                        54                 1  

[5 rows x 58 columns]

In [3]:
#check number of rows and columns in dataset
spam_email_data.shape

(4600, 58)

Data Cleaning Process
1. Dropping duplicates if any are present

In [4]:
#checking for duplicates and dropping them
spam_email_data = spam_email_data.drop_duplicates()
display(spam_email_data)

word_freq_make  word_freq_address  word_freq_all  word_freq_3d  \
0               0.21               0.28           0.50           0.0   
1               0.06               0.00           0.71           0.0   
2               0.00               0.00           0.00           0.0   
3               0.00               0.00           0.00           0.0   
4               0.00               0.00           0.00           0.0   
...              ...                ...            ...           ...   
4595            0.31               0.00           0.62           0.0   
4596            0.00               0.00           0.00           0.0   
4597            0.30               0.00           0.30           0.0   
4598            0.96               0.00           0.00           0.0   
4599            0.00               0.00           0.65           0.0   

      word_freq_our  word_freq_over  word_freq_remove  word_freq_internet  \
0              0.14            0.28              0.21                0.07   
1              1.23            0.19              0.19                0.12   
2              0.63            0.00              0.31                0.63   
3              0.63            0.00              0.31                0.63   
4              1.85            0.00              0.00                1.85   
...             ...             ...               ...                 ...   
4595           0.00            0.31              0.00                0.00   
4596           0.00            0.00              0.00                0.00   
4597           0.00            0.00              0.00                0.00   
4598           0.32            0.00              0.00                0.00   
4599           0.00            0.00              0.00                0.00   

      word_freq_order  word_freq_mail  ...  char_freq_;  char_freq_(  \
0                0.00            0.94  ...        0.000        0.132   
1                0.64            0.25  ...        0.010        0.143   
2                0.31            0.63  ...        0.000        0.137   
3                0.31            0.63  ...        0.000        0.135   
4                0.00            0.00  ...        0.000        0.223   
...               ...             ...  ...          ...          ...   
4595             0.00            0.00  ...        0.000        0.232   
4596             0.00            0.00  ...        0.000        0.000   
4597             0.00            0.00  ...        0.102        0.718   
4598             0.00            0.00  ...        0.000        0.057   
4599             0.00            0.00  ...        0.000        0.000   

      char_freq_[  char_freq_!  char_freq_$  char_freq_#  \
0             0.0        0.372        0.180        0.048   
1             0.0        0.276        0.184        0.010   
2             0.0        0.137        0.000        0.000   
3             0.0        0.135        0.000        0.000   
4             0.0        0.000        0.000        0.000   
...           ...          ...          ...          ...   
4595          0.0        0.000        0.000        0.000   
4596          0.0        0.353        0.000        0.000   
4597          0.0        0.000        0.000        0.000   
4598          0.0        0.000        0.000        0.000   
4599          0.0        0.125        0.000        0.000   

      capital_run_length_average  capital_run_length_longest  \
0                          5.114                         101   
1                          9.821                         485   
2                          3.537                          40   
3                          3.537                          40   
4                          3.000                          15   
...                          ...                         ...   
4595                       1.142                           3   
4596                       1.555                           4   
4597                       1.404                      

2. Create a dataframe with all training data except the target column

In [5]:
X = spam_email_data.drop(columns=["spam_or_not_spam"])
display(X)

word_freq_make  word_freq_address  word_freq_all  word_freq_3d  \
0               0.21               0.28           0.50           0.0   
1               0.06               0.00           0.71           0.0   
2               0.00               0.00           0.00           0.0   
3               0.00               0.00           0.00           0.0   
4               0.00               0.00           0.00           0.0   
...              ...                ...            ...           ...   
4595            0.31               0.00           0.62           0.0   
4596            0.00               0.00           0.00           0.0   
4597            0.30               0.00           0.30           0.0   
4598            0.96               0.00           0.00           0.0   
4599            0.00               0.00           0.65           0.0   

      word_freq_our  word_freq_over  word_freq_remove  word_freq_internet  \
0              0.14            0.28              0.21                0.07   
1              1.23            0.19              0.19                0.12   
2              0.63            0.00              0.31                0.63   
3              0.63            0.00              0.31                0.63   
4              1.85            0.00              0.00                1.85   
...             ...             ...               ...                 ...   
4595           0.00            0.31              0.00                0.00   
4596           0.00            0.00              0.00                0.00   
4597           0.00            0.00              0.00                0.00   
4598           0.32            0.00              0.00                0.00   
4599           0.00            0.00              0.00                0.00   

      word_freq_order  word_freq_mail  ...  word_freq_conference  char_freq_;  \
0                0.00            0.94  ...                   0.0        0.000   
1                0.64            0.25  ...                   0.0        0.010   
2                0.31            0.63  ...                   0.0        0.000   
3                0.31            0.63  ...                   0.0        0.000   
4                0.00            0.00  ...                   0.0        0.000   
...               ...             ...  ...                   ...          ...   
4595             0.00            0.00  ...                   0.0        0.000   
4596             0.00            0.00  ...                   0.0        0.000   
4597             0.00            0.00  ...                   0.0        0.102   
4598             0.00            0.00  ...                   0.0        0.000   
4599             0.00            0.00  ...                   0.0        0.000   

      char_freq_(  char_freq_[  char_freq_!  char_freq_$  char_freq_#  \
0           0.132          0.0        0.372        0.180        0.048   
1           0.143          0.0        0.276        0.184        0.010   
2           0.137          0.0        0.137        0.000        0.000   
3           0.135          0.0        0.135        0.000        0.000   
4           0.223          0.0        0.000        0.000        0.000   
...           ...          ...          ...          ...          ...   
4595        0.232          0.0        0.000        0.000        0.000   
4596        0.000          0.0        0.353        0.000        0.000   
4597        0.718          0.0        0.000        0.000        0.000   
4598        0.057          0.0        0.000        0.000        0.000   
4599        0.000          0.0        0.125        0.000        0.000   

      capital_run_length_average  capital_run_length_longest  \
0                          5.114                         101   
1                          9.821                         485   
2                          3.537                          40   
3                          3.537                          40   
4                          3.000              

3. Checking for null values

In [6]:
null_values = X.isnull().sum()
null_values

word_freq_make                0
word_freq_address             0
word_freq_all                 0
word_freq_3d                  0
word_freq_our                 0
word_freq_over                0
word_freq_remove              0
word_freq_internet            0
word_freq_order               0
word_freq_mail                0
word_freq_receive             0
word_freq_will                0
word_freq_people              0
word_freq_report              0
word_freq_addresses           0
word_freq_free                0
word_freq_business            0
word_freq_email               0
word_freq_you                 0
word_freq_credit              0
word_freq_your                0
word_freq_font                0
word_freq_000                 0
word_freq_money               0
word_freq_hp                  0
word_freq_hpl                 0
word_freq_george              0
word_freq_650                 0
word_freq_lab                 0
word_freq_labs                0
word_freq_telnet              0
word_fre

K-NN Model

In [7]:
#separate target values
y = spam_email_data['spam_or_not_spam'].values

#view target values
y[0:10]

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int64)

In [8]:
# Splitting the dataset into the Training set and Test set
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [9]:
# Fitting classifier to the Training set
knn = KNeighborsClassifier(n_neighbors = 5)
knn.fit(X_train,y_train)

KNeighborsClassifier()

In [10]:
# Predicting the Test set results
y_pred = knn.predict(X_test)
y_pred

array([1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1,
       0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0,
       0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0,
       1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0,
       1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0,
       0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1,
       0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0,

In [11]:
# Making the Confusion Matrix
cm = confusion_matrix(y_test, y_pred)
cm

array([[432,  63],
       [ 97, 250]], dtype=int64)

In [24]:
#printing the f1,... scores
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.82      0.87      0.84       495
           1       0.80      0.72      0.76       347

    accuracy                           0.81       842
   macro avg       0.81      0.80      0.80       842
weighted avg       0.81      0.81      0.81       842

[[432  63]
 [ 97 250]]
